### PR TITLE
Improve Accessibility

### PR DESCRIPTION
**Pull request by harshi0102**
Report:

Page Title: The page title was added with the logo image to improve recognition. [Click Here to see the link](https://github.com/harshi0102/Portfolio-Microverse-project/blob/accessibility/index.html#L9  ) 

Image Text Alternatives: Alt text was added to all images to provide text alternatives.
[Click here to see the link](https://github.com/harshi0102/Portfolio-Microverse-project/blob/accessibility/index.html#L42. 
)

Text Headings: No issues found 
Color Contrast: No issues found
Resize: No issues were found
Interaction: No issues found
Moving Content: No issues found
Multimedia: No issues found .
Basic Structure of the Page: No issues found.

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @harshi0102, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - No linter issues. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] You did a great job adding the accessibility features, but as the project required, please add the [link to the corresponding line of code in your pull request report](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148), so you can understand better the GitHub Pull Request features and make a more professional report.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by qusai122** [comment]
Hello, @leonardodiasb can you clarify more about what we need to do?

**Comment by harshi0102** [comment]
I added the link to the corresponding line of code in my pull request report as per the previous feedback.

**Review by Shisui6 — APPROVED** [review]
Hi @harshi0102 and @qusai122, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights
- Descriptive report ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
